import Head from 'next/head'
import Image from 'next/image'
import { pics } from '../componets/productCard/image'
import ProductList from '../componets/productCard/productList'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Next ECom</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Store</h1>
        <ul><ProductList pics={pics}/></ul>
      </main>
    </div>
  )
}