import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Product from '../componets/productCard/product'
import {pics} from '../componets/productCard/image'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Next ECom</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Store</h1>
        <Product id={pics[0].id} name={pics[0].picName} price={pics[0].price} disc={pics[0].discription}/>
      </main>
    </div>
  )
}
